TINSEL_ROOT=$(realpath ../tinsel/)

# SPDX-License-Identifier: BSD-2-Clause
APP_CPP = Heat.cpp
APP_HDR = Heat.h
RUN_CPP = Run.cpp Colours.cpp
RUN_H = Colours.h

include $(TINSEL_ROOT)/apps/POLite/util/polite.mk
